language: java
jdk:
    - oraclejdk8

script:
  - wget https://downloads.typesafe.com/typesafe-activator/1.3.10/typesafe-activator-1.3.10-minimal.zip
  - unzip typesafe-activator-1.3.10-minimal.zip
  - typesafe-activator-1.3.10-minimal/activator compile
  - typesafe-activator-1.3.10-minimal/activator test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
