language: java

sudo: required

jdk: 
  - oraclejdk8

addons:
  postgresql: "9.4"
    
services:
  - postgresql
  
before_script:
  - psql -c 'create database oauth;' -U postgres
  - psql oauth -c 'create schema oauth;' -U postgres

script:
  - wget --secure-protocol=TLSv1 https://downloads.typesafe.com/typesafe-activator/1.3.10/typesafe-activator-1.3.10-minimal.zip
  - unzip typesafe-activator-1.3.10-minimal.zip
  - activator-1.3.10-minimal/activator compile
  - activator-1.3.10-minimal/activator test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
